### ISSUE TITLE
Manual install doc does not mention need to edit config/database.yml

### ISSUE THREAD

**Issue by litlfred** [instedd/resourcemap#825]
I was getting the error below until I edited config/database.yml to set the mysql username and password.

litlfred@masala:/opt/resource_map$ script/bundle exec rake db:migrate RAILS_ENV=production
/opt/resource_map/.bundle/gems/bundler-1.7.12/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /opt/resource_map in PATH, mode 040777
rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: NO)
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/mysql2-0.3.16/lib/mysql2/client.rb:70:in `connect'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/mysql2-0.3.16/lib/mysql2/client.rb:70:in `initialize'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/connection_handling.rb:87:in `connection'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:909:in `initialize'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:807:in `new'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:807:in `up'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/migration.rb:785:in `migrate'
/opt/resource_map/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.7/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by litlfred** [comment]
My bad on this one.  I misread the install instructions.
